[package]
name = "insurance_platform"
version = "1.0.0"
authors = ["aptoss@chainsure.com"]

[addresses]
insurance_platform = "0xecc9ec84de9913e9b303e5aad94665abe1673830344ec13f3b36aeee3f45e845"
aptos_token_objects = "0x4"

[dev-addresses]
insurance_platform = "0x42"
aptos_token_objects = "0x4"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/move-stdlib"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
