[package]
name = "insurance_platform"
version = "1.0.0"
authors = ["aptoss@chainsure.com"]

[addresses]
insurance_platform = "0x3c460abe9c8906f2d81b87c4d82aaaeea988733f9f10597beda9f2143c8336bc"
aptos_token_objects = "0x4"

[dev-addresses]
insurance_platform = "0x42"
aptos_token_objects = "0x4"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/move-stdlib"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
